export const AUCTION_CONFIG = {
  INITIAL_BUDGET: 1000,
  MIN_BID: 50,
  MAX_BID: 750,
  MIN_INCREMENT: 25,
  TEAM_SIZE: 6,

  TIMER_SECONDS: 30,
  BID_EXTENSION_SECONDS: 5,

  BID_COOLDOWN_SECONDS: 2,
};